add bugzilla component to OWNERS
openshift/cluster-autoscaler-operator pull request #172
Opened 2020-10-08 20:42 UTC by elmiko

This change adds the bugzilla component name to the OWNERS file to
comply with the prodsec requirements for OpenShift builds through ART.

2020-10-08 20:43 UTC, elmiko commented
/cherry-pick release-4.6
/cherry-pick release-4.5

2020-10-08 21:11 UTC, elmiko commented
/cherry-pick release-4.5

2020-10-09 08:57 UTC, JoelSpeed commented
Should we also be including the subcomponent on this?

2020-10-09 12:47 UTC, elmiko commented
for this one i think we should not include the subcomponent. subcomponent is optional and the cao could be related in bugzilla to other providers as well (eg ovirt, openstack).

2020-10-09 13:04 UTC, JoelSpeed commented
Technically I think we should have a separate component for CAO, but I would expect any bug that is for the CAO (not the CA) to be related to the cluster-infrastructure team, not any provider team in particular

2020-10-09 13:06 UTC, elmiko commented
i tend to agree about having a separate component, or maybe just a separate subcomponent. imo, considering that "subcomponent" in the OWNERS is optional, we should opt to not use it to ensure we aren't over-scoping.

2020-10-09 13:08 UTC, JoelSpeed commented
/approve

2020-10-13 14:52 UTC, michaelgugino requested changes
/lgtm cancel

2020-10-13 14:53 UTC, michaelgugino commented
I don't think the subcomponent is actually optional.  BZ usually complains when I try to create a bug without setting it.

2020-10-15 14:01 UTC, michaelgugino approved these changes
/lgtm

2020-10-15 14:51 UTC, merged