Annotate manifests for single-node-developer cluster profile
openshift/cluster-autoscaler-operator pull request #188
Opened 2020-12-03 15:18 UTC by cfergeau

This partially implements phase 1 of https://github.com/openshift/enhancements#482
and does not change behavior. Initially, all cluster-autoscaler-operator
manifests are included in the single-node-developer cluster profile.
Follow-on PRs may exclude any of these that are not needed in the
profile.

2020-12-07 08:59 UTC, cfergeau commented
/retest

2020-12-09 17:23 UTC, cfergeau commented
/retest

2020-12-17 08:49 UTC, cfergeau commented
/retest

2021-01-04 19:26 UTC, rkukura commented
/retest

2021-01-04 19:30 UTC, elmiko commented
hey, i just took a quick look at this and it looks ok to me but i want to read up on the enhancement a little more.

2021-01-04 21:18 UTC, elmiko requested changes
after reading through the enhancement, i do not think we should be including the autoscaler components in the single node profile.

firstly, given the goals described in that doc the autoscaler should not be used with the single node profile.

secondly, the machine-api-operator is called out specifically as not being included and the autoscaler would require the machine-api to operate..

i think we should mark this component as false, or exclude it from inclusion in the single node profile. it wasn't clear to me from reading the enhancement if we should use the `include.release.openshift.io/single-node-developer: "false"` annotation at this time or if we should just not add it to this component.

2021-01-06 14:39 UTC, cfergeau commented
For now, we are including everything in the single-node-developer profile, as before disabling components, we need to make sure nothing requires it during the installation. But I agree that eventually it's likely we'll disable this.
See https://github.com/openshift/machine-api-operator/pull/774#issuecomment-740527434 for the corresponding machine-api discussion.

2021-01-06 15:00 UTC, elmiko commented
thanks for the clarification @cfergeau
/approve

2021-01-13 16:19 UTC, cfergeau commented
/bugzilla refresh

2021-01-13 16:19 UTC, cfergeau commented
> thanks for the clarification @cfergeau
> /approve

Can you also add a /lgtm? Or is this going to be done by a second reviewer?

2021-01-13 17:02 UTC, JoelSpeed commented
/lgtm

2021-01-14 08:08 UTC, cfergeau commented
/retest

2021-01-14 13:22 UTC, cfergeau commented
/retest

2021-01-14 15:22 UTC, merged